[build]
  publish = "."

# --- Subdomain redirects ---
[[redirects]]
  from = "https://viccar.netlify.app/*"
  to = "https://blablacar.lol/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://viccar.netlify.app/*"
  to = "https://blablacar.lol/:splat"
  status = 301
  force = true
